# Generated by Django 4.2.1 on 2023-06-10 19:52

from django.conf import settings
from django.db import migrations, models
import shopapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0007_alter_product_options_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=models.SET(shopapp.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
