# Generated by Django 4.2.1 on 2023-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAdressLastReqTime',
            fields=[
                ('IP_address', models.GenericIPAddressField(primary_key=True, serialize=False, unique=True)),
                ('last_req_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
